version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://btdemande:btdemande@db:3306/btdemande?serverVersion=mariadb-11.4.0&charset=utf8mb4
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_CHAT_MODEL: ministral-3:3b
    depends_on:
      - db
      - ollama
    networks:
      - symfony

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony_nginx
    ports:
      - 7070:80
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php
    networks:
      - symfony
      - dokploy-network
    labels:
      traefik.enable=true
      traefik.http.routers.btdemande-http.rule=Host(`btdemande-btdemande-3clxoz-d2cc8e-187-124-33-225.traefik.me`)
      traefik.http.routers.btdemande-http.entrypoints=web
      traefik.http.services.btdemande-http.loadbalancer.server.port=80

  db:
    image: mariadb:11.4
    container_name: symfony_db
    environment:
      MARIADB_DATABASE: btdemande
      MARIADB_USER: btdemande
      MARIADB_PASSWORD: btdemande
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: btdemande
      PMA_PASSWORD: btdemande
    ports:
      - 4040:80
    depends_on:
      - db
    networks:
      - symfony

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - symfony

volumes:
  db_data: null
  ollama_data: null

networks:
  symfony: null
  dokploy-network:
    external: true