parameters:
    documents_directory: '%kernel.project_dir%/public/uploads/documents'
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
    documents_path: '%kernel.project_dir%/var/documents'
    app.docs_directory: '%env(resolve:UPLOAD_DIR)%'
    UPLOAD_DIR_rag: '%kernel.project_dir%/public/uploads/documents'


    gmail_credentials_path: '%kernel.project_dir%/config/google/credentials.json'
    gmail_token_path: '%kernel.project_dir%/config/google/token.json'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # Services avec arguments spécifiques
    App\Service\InseeApiService:
        arguments:
            $inseeApiKey: '%env(INSEE_API_KEY)%'

    App\Service\GoogleCalendarService:
        arguments:
            $credentialsPath: '%gmail_credentials_path%'
            $tokenPath: '%gmail_token_path%'


    App\Command\RdvStartupCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    
    App\Service\DocumentRagStrictQaService:

    App\Service\GmailService:
        arguments:
            $credentialsPath: '%gmail_credentials_path%'
            $tokenPath: '%gmail_token_path%'

    App\Service\RagTestService:
        arguments:
            $docsDirectory: '%app.docs_directory%'  
            $openAiApiKey: '%env(OPENAI_API_KEY)%'

    App\Service\LlmService:
        arguments:
            $apiKey: '%env(APP_LLM_OPENAI_API_KEY)%'
            $baseUrl: '%env(APP_LLM_OPENAI_API_BASE_URL)%'
            $model: '%env(APP_LLM_OPENAI_MODEL)%'


    # --- Ollama Embeddings (LLPhant) ---
    App\Service\ServiceOllamaEmbeddingGenerator:
        arguments:
            $baseUrl: '%env(resolve:OLLAMA_BASE_URL)%'
            $model: '%env(resolve:OLLAMA_EMBED_MODEL)%'
            $embeddingLength: '%env(int:OLLAMA_EMBED_DIM)%'

    
    LLPhant\Embeddings\EmbeddingGenerator\EmbeddingGeneratorInterface: '@App\Service\ServiceOllamaEmbeddingGenerator'

    App\Schedule\GmailSchedule:
        tags: ['schedule.provider']

    App\Security\ApiJwtTokenManager:
        arguments:
            $secret: '%env(API_JWT_SECRET)%'
